version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1432:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd#Secur3!"
      ACCEPT_EULA: "Y"