on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Run unit tests
        run: dotnet test ./WebshopBackend.UnitTests/WebshopBackend.UnitTests.csproj --configuration Release
        
  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          services: |
            sql-server-db

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Run integration tests
        run: dotnet test ./WebshopBackend.IntergrationTests/WebshopBackend.IntergrationTests.csproj --configuration Release

  sonar-code-analysis:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=sprint-3-individual-project
              -Dsonar.projectKey=Backend
              -X
      